# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - pandoc
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry==1.3.2
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group.
      - poetry install --no-root --only docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py
