[tool.poetry]
name = "ska-pydada"
version = "0.11.0"
description = "SKA Pulsar DADA Library"
authors = [
    "Andrew Jameson <ajameson@fourierspace.com.au>",
    "Jesmigel Cantos <jesmigel.developer@gmail.com>",
    "Will Gauvin <wgauvin@swin.edu.au>",
    "Willem van Straten <wvanstraten@fourierspace.com.au>"

]
license = "BSD-3-Clause"
readme = "README.md"
packages = [
  { include = "ska_pydada", from ="src" },
]

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'


[tool.poetry.dependencies]
python = ">=3.10,<3.12"
readerwriterlock = "^1"
backoff = "^2"
pandas = "^2"
jinja2 = "^3"
watchdog = "^3"
nptyping = "*"
numpy = "^1.23.2"
overrides = "*"

[tool.poetry.group.notebooks.dependencies]
matplotlib = "^3"
ipywidgets = "*"
ipympl = "*"

[tool.poetry.group.dev.dependencies]
astropy = "*"
autoflake = "*"
backoff = "*"
black = "*"
coverage = "*"
docformatter = "*"
flake8 = "*"
flake8-black = "*"
flake8-docstrings = "*"
flake8-formatter-junit-xml = "*"
flake8-rst-docstrings = "*"
ipython = "*"
isort = "*"
mock = "*"
mypy = "*"
nbmake = "*"
nbqa = "*"
pandas-stubs = "*"
pyflakes = "*"
pylint = "*"
pylint-junit = "*"
pytest = "*"
pytest-bdd = "*"
pytest-cov = "*"
pytest-forked = "*"
pytest-json-report = "*"
pytest-metadata = "*"
pytest-mock = "*"
pytest-pycodestyle = "*"
pytest-pydocstyle = "*"
pytest-pylint = "*"
pytest-runner = "*"
requests = "*"
types-pyyaml = "*"
types-requests = "*"
types-urllib3 = "*"
flaky = "*"

[tool.poetry.group.jupyterlab.dependencies]
jupyter = "*"
jupyterlab = "*"

[tool.poetry.group.docs.dependencies]
sphinx-rtd-theme = "*"
sphinxcontrib-plantuml = "*"
sphinx-autodoc-typehints = "*"
docutils = "<0.18"
markupsafe = "<2.1.0"
sphinx = "*"
exhale = "*"
breathe = "*"
transitions = "*"
typing-extensions = "*"
recommonmark = "*"
sphinx-markdown-tables = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
